### ISSUE TITLE
Server Configuration

### ISSUE THREAD

**Issue by ConnorJC3** [pieterlange/kube-openvpn#10]
It would be great if I could somehow edit the server config to add my own options. As it stands I have very little control over what goes in the config file.

For example, I'd like to add these lines to my server config:
```
remote-cert-eku "TLS Web Client Authentication"
tls-version-min 1.2
cipher AES-256-CBC
auth SHA-256
tls-cipher TLS-DHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-256-CBC-SHA256 
```

However, those won't be for everybody, as some people will need to use an OpenVPN client before version 2.3.3.

**Comment by pieterlange** [comment]
You're right. I shouldn't evaluate the config in-place as you can't mount in the config as ConfigMap. (Well, you can, but it will get replaced.)

I pushed [feature/config-template](https://github.com/pieterlange/kube-openvpn/tree/feature/config-template). The feature is built in image `quay.io/plange/openvpn:feature_config-template`.

You can use your own config by creating a [ConfigMap](http://kubernetes.io/docs/user-guide/configmap/) using: `kubectl create configmap openvpn-template --from-file=openvpn.tmpl`. Mount the config into the pod at `/etc/openvpn/templates/` by adding a volumemount. You can copy the ccd config and replace "ccd" with "template".

Hope this helps! Will keep the branch open if this needs some more tweaks.

**Comment by pieterlange** [comment]
However, if you want to add configurations specific to certain users you should add it in the `openvpn-ccd` configmap at the key that corresponds with the CN of the client. (See the `client-config-dir` directive in the [openvpn manual](client-config-dir))

**Comment by pieterlange** [comment]
I think this is fixed now, but feel free to reopen.
