### ISSUE TITLE
Clients can use VPN for all outgoing traffic

### ISSUE THREAD

**Issue by pieterlange** [pieterlange/kube-openvpn#17]
Even though we only push routes for the pod and service networks, clients can still route all their traffic through the VPN tunnel and we'll happily masq it.

This may be desirable for some people but i think the default behavior should be to deny traffic to networks other than the pod and service cidrs.

**Comment by pieterlange** [comment]
This is fixed, but i'm leaving the issue open for further discussion on default behaviour and further feature requests.

**Comment by r4j4h** [comment]
I think this is the right way to go, but I do think it would be enhanced by some documentation around the `OVPN_DEFROUTE` environment variable switch you added so that users can more easily choose which fits for them.

**Comment by pieterlange** [comment]
Added a note in FAQ. There are now 3 config options for `$OVPN_DEFROUTE`
  * 0 - Only route kubernetes network and don't allow other traffic
  * 1 - Allow clients to route to other network but don't push this config option to the clients (meant for road warriors)
  * 2 - Force all traffic through VPN (if client allows push options)
