### ISSUE TITLE
Moving deploy.sh into image

### ISSUE THREAD

**Issue by cemo** [pieterlange/kube-openvpn#33]
The current way of deploying openvpn is that cloning project and running commands. If deploy.sh would be moved into the image, there will be no need to clone project. This is might be considered as a temporary improvement before moving into a chart.

**Comment by pieterlange** [comment]
I want the image itself to stay as barebones as possible so i don't think i'll do this.

**Comment by cemo** [comment]
The problem is that cloning repo is tedious and error-prone. Using commands would be cooler. Given the fact that this image is providing k8s related implementation, having a file producing necessary manifests is not problem. 

This also makes more consistent across repo and other commands. Repo or image might be outdated. In case such an inconsistency might create a problem.

**Comment by pieterlange** [comment]
I'm re-evaluating openvpn PKI initialization and will take your comments into account. I will not cover this proposed workflow however. (temporary stuff tends to stay forever)
