### ISSUE TITLE
document deploying existence openvpn configurations

### ISSUE THREAD

**Issue by cemo** [pieterlange/kube-openvpn#35]
It would be better to have a document related to deployment of already set up infrastructure.

**Comment by pieterlange** [comment]
With the abstractions currently provided in this deployment i think it should be really easy to port existing openvpn installations to kube-openvpn:

- Copy your existing openvpn.conf into openvpn.tmpl (as configmap, mount to `/etc/openvpn/templates`). Optionally replace any static variables by environment variables.
- Copy your ca.crt and server credentials into the Secret `openvpn-pki` (optionally also add your dh.pem and/or ta.key)
- Reroute your DNS to the loadbalancer exposing kube-openvpn

I haven't documented this procedure and i'm not sure if i want to plan on doing so - it should be fairly simple but it breaks away from a default "fool proof" setup procedure and may introduce all kinds of new problems that i don't feel like debugging. ;-)

People are welcome to share their success/fail stories in this issue though!

**Comment by pieterlange** [comment]
I feel that anyone who's serious about doing a migration like this should be able to pull together a PR :nerd_face:. Which i'll happily merge, but i doubt it will involve anything more than what's described in my comment above. Please reopen when that happens to be the case.
