### ISSUE TITLE
Accessing nodes by ssh

### ISSUE THREAD

**Issue by cemo** [pieterlange/kube-openvpn#37]
I can access services on my k8s cluster and ping pods but I can not ssh nodes where services are locating. I can also not access database services which are outside of the cluster but inside in the same subnet. How can I configure to access them?

**Comment by pieterlange** [comment]
https://github.com/pieterlange/kube-openvpn/blob/master/docs/FAQ.md#i-want-to-route-all-traffic-through-the-vpn

**Comment by cemo** [comment]
I had actually checked it too. Sorry to bother. Thanks for your time.

**Comment by pieterlange** [comment]
No problem. You can ping me on the kubernetes slack as well :)

**Comment by pieterlange** [comment]
You can now also add the host IP range to `$OVPN_ROUTES` so you can SSH to the hosts, without having to route ALL traffic through the VPN. (See 49a3dbb78b0de790ce10f2a12be3747200e44da3)
