### ISSUE TITLE
Generate certificates locally then kubectl

### ISSUE THREAD

**Issue by deimosfr** [pieterlange/kube-openvpn#42]
Hi,

I think it would be more interesting to generate certificates locally and then use kubectl to push them.

In some case you can't directly access the API server but could deploy the files in another fashion, I think getting files locally could really be useful. Other deployment method could then be used to perform the deployment.

I've done this already, would you be interrested by a pull request ?

Thanks

**Comment by pieterlange** [comment]
Certificates are currently generated locally by the system administrator, so it's unclear to me what you mean. A PR might clear things up.

I'm planning on making this project use the "operator" deployment style which should solve a lot of these issues but i currently don't have the time to do it.

**Comment by deimosfr** [comment]
Sorry, you're right, certificates are locally, but not kubernetes configuration. Instead of passing directly to kubectl, I propose to store configuration locally and then pushing through kubectl.

**Comment by pieterlange** [comment]
Discussed on slack. Clarifying for posterity:

@deimosfr is looking for an intermediate step in generating the kubernetes resources so the generated objects can be moved to some custom deployment system (be that an actual system or a different person that has direct access to the cluster).

This is probably useful for others as well, but it should be noted that i want to change the entire deployment model at some point.
