### ISSUE TITLE
Revoking does not drop active connections

### ISSUE THREAD

**Issue by pasali** [pieterlange/kube-openvpn#49]
I have started my openvpn server with `--crl-verify` parameter. After revoked a client, if client disconnects and try to connect again it works as expected. But if client does not disconnect openvpn does not drop active connection.

**Comment by pasali** [comment]
In the OpenVPN docs; it says that CRL file will be re-read on renegotiation. Default renegotiation period 1 hour. Should  i need to set it a smaller period to drop active connection? Or is this the right way to do it ?

**Comment by pieterlange** [comment]
This is normal openvpn behavior. If you want to you can explicitly drop client connections over the management port.

We could automate this when i get around to making a kubernetes operator out of this project, but that's a long way off.
