### ISSUE TITLE
Connection visibility

### ISSUE THREAD

**Issue by hwinkel** [pieterlange/kube-openvpn#5]
Hi, great stuff! just deploying the OVPN endpint.

Do you have any idea, plan how to show the currently connected use? may integrate wit a existing OPenvpn tool?

**Comment by pieterlange** [comment]
You can view who's connected through the server logs emitted on `STDOUT`.

If you want to do analysis of the network traffic you may pair the vpn service with [packetbeat](https://www.elastic.co/products/beats/packetbeat) by adding [my packetbeat](https://github.com/pieterlange/docker-packetbeat) docker as a sidecar to the openvpn pod. Note that you need permission to do this in many jurisdictions.

**Comment by pieterlange** [comment]
You can now also execute `docker run -e OVPN_SERVER_URL=tcp://vpn.my.fqdn:1194 -v $PWD:/etc/openvpn -ti ptlange/openvpn ovpn_listclients` to list currently issued valid certs.

I hope this answers your questions. You may close the issue or further specify what visibility you're missing.

**Comment by hwinkel** [comment]
Many thanks for now...
