### ISSUE TITLE
empty .ovpn user file asking for OVPN_SERVER_URL

### ISSUE THREAD

**Issue by hwinkel** [pieterlange/kube-openvpn#6]
After trying to create the users .ovpn in then last step the file only contains a message saying:

"Need to pass in OVPN_SERVER_URL in 'proto://fqdn:port' format"

**Comment by pieterlange** [comment]
Thanks for the report! 

The command used should include the `OVPN_SERVER_URL` environment variable. So instead of running:

``` sh
docker run -v $PWD:/etc/openvpn --rm ptlange/openvpn ovpn_getclient CLIENTNAME > CLIENTNAME.ovpn
```

You should execute:

``` sh
docker run -e OVPN_SERVER_URL=tcp://vpn.example.com:1194 -v $PWD:/etc/openvpn --rm ptlange/openvpn ovpn_getclient CLIENTNAME > CLIENTNAME.ovpn
```

**Comment by hwinkel** [comment]
expected something like this. many thanks for the ultra quick response
