### ISSUE TITLE
openvpn-ingress isn't created on deploy

### ISSUE THREAD

**Issue by lake-effect** [pieterlange/kube-openvpn#60]
Expected behavior from README:

```
$ ./kube/deploy.sh default tcp://vpn.my.fqdn:1194 10.3.0.0/24 10.2.0.0/16
secret "openvpn-pki" created
configmap "openvpn-settings" created
configmap "openvpn-ccd" created
deployment "openvpn" created
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:30xxx) to serve traffic.

See http://releases.k8s.io/release-1.3/docs/user-guide/services-firewalls.md for more details.
service "openvpn-ingress" created
```

Actual behavior:

```
$ ./kube/deploy.sh default tcp://<domain redacted>.com:1194 <service and pod cidrs redacted>

Generating Kubernetes resources
Creating and applying Kubernetes resources
configmap "openvpn-crl" created
configmap "openvpn-ccd" created
configmap "openvpn-portmapping" created
secret "openvpn-pki" created
configmap "openvpn-settings" created
service "openvpn" created
deployment "openvpn" created
```

I otherwise followed the README from top to bottom.

**Comment by pieterlange** [comment]
Yeah the installation instructions aren't perfect; i only deploy a `NodePort` service because of cloud costs incurred.

The docs do state this:
> Your VPN endpoint is now reachable on every node in the cluster on port 30XXX. This port can be easily exposed by setting the Type field of the openvpn Service to LoadBalancer if you're running your cluster within a public cloud. Assign the correct CNAME/A address to your loadbalancer or replace the original servername with the DNS name of your newly created loadbalancer in your client configuration.

Working (slowly) on better deployment methods, but thats mostly dependent on the operator framework getting into a better place than `pre-alpha`.

**Comment by lake-effect** [comment]
No problem, that's understandable. Thanks for clarifying!
