### ISSUE TITLE
State of the art method

### ISSUE THREAD

**Issue by zzvara** [pieterlange/kube-openvpn#67]
Is there a more recent and more easily used method to accomplish the same goals that this code is intended?

**Comment by pieterlange** [comment]
This is a rather ambiguous question so i'm not sure how to answer it.

There are some pain points (difficulty) in deploying kube-openvpn, but that's mostly centered around secrets/PKI management. PKI management is hard, and the people in-the-know have their own preferences for doing this so i left this out of scope for this project (other than bundling easyrsa).

The state of the art is to deploy your apps using [operators](https://coreos.com/operators) and while i did put in some effort to make a [WIP attempt of writing an operator for openvpn](https://github.com/pieterlange/openvpn-operator), to be honest the "in progress" part is mostly stalled. I may pick it up again if i actually find more of a business need to continue development on it.

Assuming this is a sufficient answer, i'm closing this ticket. If you have further questions, please make more of an attempt to describe your usecase :-).
