### ISSUE TITLE
Accessing clients from pods

### ISSUE THREAD

**Issue by pdostal** [pieterlange/kube-openvpn#69]
Hello @pieterlange,

first of all thank you for this nice openVPN deployment!
I just have a question about accessing mapped client's port.

The `openvpn` pod has in my case IP `192.168.186.186` and I can access the client port through this IP but I'm not sure if this one is fixed and I don't know it's DNS name either.
There is `openvpn.default.svc.cluster.local` DNS name but it points to `10.100.163.106` which does not listen on the client port.

Can you suggest which IP / DNS name I should use in my pods?

Thank you

**Comment by pieterlange** [comment]
You can create `Service`s to map arbitrary ports to the openvpn pod(s). Say you want to expose a HTTP service on a VPN client to the pods in your cluster, you could create a new service to do that. Example in [kube/routeme.yaml](https://github.com/pieterlange/kube-openvpn/blob/master/kube/routeme.yaml).
